name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
        - main

jobs:
    system_info:
        runs-on: ubuntu-latest
        steps:
            - name: Hello
              run: echo "hello"
        
        

